const labelDetail = {
    "điện thoại": [
        "màn hình",
        "hệ điều hành",
        "camera sau",
        "camera trước",
        "chip",
        "RAM",
        "dung lượng lưu trữ",
        "sim",
        "pin, sạc",
    ],
    laptop: [
        "CPU",
        "RAM",
        "ổ cứng",
        "màn hình",
        "card màn hình",
        "cổng kết nối",
        "hệ điều hành",
        "thiết kế",
        "kích thước, khối lượng",
        "thời điểm ra mắt",
    ],
    tablet: [
        "màn hình",
        "hệ điều hành",
        "chip",
        "RAM",
        "dung lượng lưu trữ",
        "kết nối",
        "sim",
        "camera sau",
        "camera trước",
        "pin, sạc",
    ],
    "đồng hồ": [
        "đối tượng sử dụng",
        "đường kính mặt",
        "chất liệu mặt kính",
        "chất liệu dây",
        "bộ máy",
        "chống nước",
        "thương hiệu",
        "hãng",
    ],
    "sạc dự phòng": [
        "hiệu suất sạc",
        "dung lượng pin",
        "thời gian sạc đầy pin",
        "nguồn vào",
        "nguồn ra",
        "công nghệ / tiện ích",
        "kích thước",
        "trọng lượng",
        "thương hiệu",
        "sản xuất tại",
        "hãng",
    ],
    "tai nghe": [
        "thời gian tai nghe",
        "thời gian hộp sạc",
        "cổng sạc",
        "công nghệ âm thanh",
        "tương thích",
        "tiện ích",
        "hỗ trợ kết nối",
        "điều khiển bằng",
        "hãng",
    ],
    "bàn phím": [
        "tương thích",
        "cách kết nối",
        "đèn LED",
        "số phím",
        "thương hiệu",
        "hãng",
    ],
    "chuột máy tính": [
        "tương thích",
        "độ phân giải mặc định",
        "cách kết nối",
        "độ dài dây / khoảng cách kết nối",
        "loại pin",
        "khối lượng",
        "thương hiệu",
        "sản xuất tại",
        "hãng",
    ],
};

export default labelDetail;
